### ISSUE TITLE
Switch db to mongo

### ISSUE THREAD

**Issue by ndrsllwngr** [andreasellw/ffp#11]
##### TODO
- [x] Apply changes of `stack new minesweepskell yesodweb/mongo` to our current project
- [x] Update github workflow
- [x] rm postgres from package.yml

fyi
- run `stack build` after checking out these changes

##### INFO
Diff between mongo and postgres
```sh
$ diff -qr ffp test/minesweepskell --exclude=".stack-work" --exclude=".*" | sort
```
###### TODO
```
Files ffp/src/Application.hs and test/minesweepskell/src/Application.hs differ
Files ffp/test/TestImport.hs and test/minesweepskell/test/TestImport.hs differ
```

###### DONE
```
Files ffp/templates/default-layout.hamlet and test/minesweepskell/templates/default-layout.hamlet differ
Files ffp/templates/homepage.hamlet and test/minesweepskell/templates/homepage.hamlet differ
Files ffp/test/Handler/CommentSpec.hs and test/minesweepskell/test/Handler/CommentSpec.hs differ
Files ffp/src/Settings.hs and test/minesweepskell/src/Settings.hs differ
Files ffp/src/Model.hs and test/minesweepskell/src/Model.hs differ
Files ffp/src/Handler/Home.hs and test/minesweepskell/src/Handler/Home.hs differ
Files ffp/src/Handler/Comment.hs and test/minesweepskell/src/Handler/Comment.hs differ
Files ffp/src/Foundation.hs and test/minesweepskell/src/Foundation.hs differ

Files ffp/stack.yaml and test/minesweepskell/stack.yaml differ
Files ffp/stack.yaml.lock and test/minesweepskell/stack.yaml.lock differ
Files ffp/minesweepskell.cabal and test/minesweepskell/minesweepskell.cabal differ
Files ffp/package.yaml and test/minesweepskell/package.yaml differ
Files ffp/config/settings.yml and test/minesweepskell/config/settings.yml differ
Files ffp/config/test-settings.yml and test/minesweepskell/config/test-settings.yml differ

Only in ffp/config: client_session_key.aes

Only in ffp/static: tmp

Only in ffp: minesweepskell.iml
Only in ffp: yesod-devel

Files ffp/README.md and test/minesweepskell/README.md differ
Only in ffp: README-yesodweb-postgres.md

Only in ffp/config: models.persistentmodels
Only in ffp/config: routes.yesodroutes
Only in test/minesweepskell/config: models
Only in test/minesweepskell/config: routes
```
