### ISSUE TITLE
Further ToDos

### ISSUE THREAD

**Issue by tmrdlt** [andreasellw/ffp#17]
##### SPRINT GOAL  ♦️
- [x] Apply lenses to Data.matrix #28 
- [x] Use actual randomSeed (either via user input or generated) #29 
- [x] Add ServerSideEvents [[Tfoo](https://github.com/nbartlomiej/tfoo/blob/7e47d3c4df3fb5929aa4810c555475b77d3bf3fb/Tfoo/Game.hs#L13), [Chan](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Concurrent-Chan.html)] to update UI instantly 🗼 #31 
- [x] Human Readable unique GameID generieren (like HarmfulExpectationsCeaseParticularly) @timunkulus 
- [x] Generate games of predefined sizes / difficulty ⚡️
- [x] Rework user interface (minimal and clean design language, remove boilerplate) #30 @ndrsllwngr @timunkulus
  - [x] Render digits using Attributes to remove flickering
  - [x] Add game instructions (controls)
  - [x] Go Back & Pause Button is just one
  - [x] Completed game history in colors
- [x] BUG: It should be possible to put only as many flags as totally available @griase94 
- [x] BUG: Show elapsed time of finished games @timunkulus 
- [x] BUG: Pause a game that has no move yet will cause timeElapsed to be already counted @timunkulus 
- [x] On reset finished game: leave game in DB and create new gameID @griase94 
- [x] Update [`README.md`](https://github.com/ndrsllwngr/ffp/blob/develop/README.md) (incl. usage, topics and short description) and align with lecture topics 🔺  https://github.com/ndrsllwngr/ffp/issues/17#issuecomment-691658596
- [x] Refactor project, cleanup code, align routes, give variables suitable names [86bae6f68869314ae5a76101267795980b866a61]
- [x] Format files with linter (e.g. `stylish-haskell -r -i src/*`), be careful that `{-# LANGUAGE` are preserved
- [x] Test project
  - [x] game logic
  - [x] moves
  - [x] interactions & routing
  - [x] warnings

##### BACKEND
- [x] Don't allow flagging of already revealed cells
- [x] Error Handling in Requests und Logik (z.b. outOfBound) ❓

##### FRONTEND
- [x] Landing page: Show total time of each game which is in final state (lost/won)

##### BUGS
- [x] Performance Issues  ❓

##### NOT DOING
- host project on heroku (https://github.com/mfine/heroku-buildpack-stack)
-  UI - implement right-click instead of alt+left-click to flag a cell
- UI - add pressed state to unrevealed cell & face status
- Leaderboard (sorted by time, grouped by size+difficulty) would be possible, if we would allow players to enter username (similar to retro game machines)
- Add unit-tests
- Error handling on route responses (e.g. show not found page)
- Make use of advanced monads
- Game page: Show move history on `/game/#id` page (🤔  not sure if useful at all. any information gain?)

<hr/>

##### DONE
- [x] View updated sich nach Move 32febbeab1e210a0acd22af1e46eb8a9f8c2ae1c
- [x] Bomben durchstreichen wenn angeklickt und danach Spiel abschließen d0b3c7d5d718e3414bc45d6f33284ce1f07653ac
 - [x] Reveal All wenn alle Bomben geflaggt wurden d0b3c7d5d718e3414bc45d6f33284ce1f07653ac
- [x] Spiel vorzeitig abschließbar machen können (Related #15) 
- [x] Zeit reinbringen und anzeigen
- [x] Reset Route and action in front end 
- [x] Add reveal all button (makeMove)
- [x] Stop timer if final state of game 10f2a25e8dc15d865baf39ae0410256e3fa3db17
- [x] add face button in the middle with different emotions
- [x] Pause Game Funktion (führt zu Startseite zurück)
- [x] Reveal all button
- [x] Anzahl an übrigen Flags anzeigen bc8684ed2e88d29604908b588b15a682dc7fda85
- [x] Spiel in Datenbank als nur ein Eintrag abspeichern https://github.com/ndrsllwngr/ffp/commit/ed7b3d218d47c2692eb685e0a73d94a38a81f384
- [x] Game Logik anpassen: Spiel ist erst gewonnen, wenn alle Flags verteilt wurden!
- [x] `localhost` is hardcoded at the moment, better solution? b2ac90bf57cff14643fdc78b1b1b163517352a93
- [x] Landing page: List all paused/ongoing games which are in the DB 2ee7cc36fa020d18501f6f797af023bb07047696
- [x] Lift state and only save paused or finished games in db #27 
- [x] Make use of lenses  #25
- [x] Make use of TVars #27 
- [x] Warnings Fixen [cb3c361c78df9b20746241b713bff8c1efcb9ffe, #26 ]

<hr/>

##### REQUIREMENTS ([Uni2Work](https://uni2work.ifi.lmu.de/course/S20/IfI/FFP/sheet/Projektanmeldung/subs/uwalft4mx5ntfoy4))
1. Webapplikation mit `yesod`
2. Monaden
> Fortgeschrittenere Themen, welche sich zu Monaden anrechnen lassen sind z.B. Monad-Transformer, Lifting, fortgeschrittene Verwendungen von Zustandsmonaden, etc.
> Beachten Sie bitte, dass zu einer zufriedenstellenden Anrechnung des Themas Monaden mehr als einfacher monadischer Code (z.B. nicht nur do-Notation) vorhanden sein muss.
3. Datenbankanbindung (`Persistent`)
> zusätzlich eine Datenbankanbindung implementieren (z.B. mit Persistent), beispielsweise um Spielstände persistent zu speichern, um zu einem späteren Zeitpunkt mit dem Spiel fortfahren zu können.
4. Tests (?)
5. ~~AI/Automated Problem Solving~~
> Das Thema KI / Automated Problem Solving ist des Weiteren nicht direkt ein Thema der funktionalen Programmierung.

###### **UPDATED REQUIREMENTS**
1. TVars (nebenläufigkeit)
> TVars decken ja eigentlich sogar auch Nebenläufiges Programmieren
2. Lenses
> Sie könnten noch ein paar Lenses für irgendwelche Datentypen (die sie ja wahrscheinlich sowieso haben) definieren und deren Verwendung demonstrieren.
3. Unlösbare Probleme (State monade)
> Die unlösbaren Probleme sind sicherlich auch ein guter Punkt, den Sie in der Abgabe ja kurz dokumentieren und begründen könnten (was geht da, warum nicht).
